version: 0.0
os: linux
files:
  - source: /shopsixle.html    #source file location in the repo.
    destination: /var/www/shopsixle       #destination location into the instance
file_exists_behavior: OVERWRITE    #If same source file exist,It will overwrite

files:
  - source: /report.html   #source file location in the repo.
    destination: /var/www/report       #destination location into the instance
file_exists_behavior: OVERWRITE    #If same source file exist,It will overwrite
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
